#!/bin/bash
#
#
#            .   .                       .-.                   .
#            |   |                      (   )                  |
#            |---| .-.  .,-. .,-. .  .   `-.  .-. .  . .--. .-.| .--.
#            |   |(   ) |   )|   )|  |  (   )(   )|  | |  |(   | `--.
#            '   ' `-'`-|`-' |`-' `--|   `-'  `-' `--`-'  `-`-'`-`--'
#                       |    |       ;
#                       '    '    `-'
#                              Commit sounds for your happiness
#                 By Roey Chasman

function run_test
{
    DIR="${HOME}/git-hooks/res"
    SOUND=` ls $DIR | while read x; do echo "\`expr $RANDOM % 1000\`:$x"; done | sort -n | sed 's/[0-9]*://' | head -1`

    afplay $DIR/$SOUND
}

case "${1}" in
    --about )
        echo -n "On commit, a random sound will play making you happy!"
        ;;
    * )
        run_test "$@"
        ;;
esac
